version: '3'

services:
  app:
    build:
      context: .
    environment:
      API_BASE_URL: https://localhost:8008
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
